export const QuestionsByPage = {
  page1: [
    "A charming street in a historic European city.",
    "A peaceful Japanese garden with cherry blossoms.",
    "A magical portal in the middle of a forest.",
    "A colorful coral reef teeming with marine life.",
    "A mysterious abandoned mansion in the woods.",
  ],
  page2: [
    "A peaceful Japanese garden with cherry blossoms.",
    "A magical portal in the middle of a forest.",
    "A colorful coral reef teeming with marine life.",
    "A mysterious abandoned mansion in the woods.",
    "A traditional Japanese tea ceremony.",
    "A picturesque lighthouse overlooking the sea.",
    "A vibrant market square in Morocco.",
    "A tranquil lake surrounded by autumn trees.",
    "A futuristic city skyline with flying cars.",
    "A cozy reading nook by a window.",
    "A group of adventurers exploring a lost city.",
    "A serene mountain lake reflecting the sunrise.",
    "A whimsical ice cream shop with unique flavors.",
    "A majestic waterfall hidden in a lush jungle.",
    "A quaint cottage covered in ivy.",
    "A bustling night market with street food vendors.",
    "A peaceful village in the countryside.",
    "A colorful hot air balloon festival.",
    "A magical forest with glowing fireflies.",
    "A charming cafe on a cobblestone street.",
  ],
  // Add more pages as needed
};
