steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "nextjs-app",
        "--image",
        "gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--set-env-vars=NODE_ENV=production",
        "--set-secrets=AZURE_OPENAI_API_KEY=azure-openai-key",
      ]
secrets:
  - kmsKeyName: projects/$PROJECT_ID/locations/global/keyRings/my-keyring/cryptoKeys/my-key
    secretEnv:
      azure-openai-key: projects/$PROJECT_ID/secrets/AZURE_OPENAI_API_KEY/versions/latest
